name: Deploy Image Processor (Dev)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
